### ISSUE TITLE
Console messages wrong - i18n problem?

### ISSUE THREAD

**Issue by xerces8** [subclipse/subclipse#10]
When I commit or update, the messages in the Console look like:

update C:/data/Foo.java -r HEAD --force
    U   C:/data/Foo.java
    notify.update
    notify.stats.file.head
    notify.stats.update
commit -m "bla bla..." -N C:/data/Bar.java C:/data/Baz.java C:/data/Fooz.java
    notify.commit.modified
    notify.commit.modified
    notify.commit.modified
    notify.commit.transmit
    Unknown action received: commit finalizing
    Committed revision 199.

Eclipse Java EE IDE for Web Developers.
Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200

  Subclipse	4.2.0.201609101435	org.tigris.subversion.subclipse.feature.group	Subclipse

**Comment by markphip** [comment]
Thanks for reporting this problem.  I have posted a new Subclipse release 4.2.1 that contains this fix.

**Comment by foxsilverfox** [comment]
I still receiving message "Unknown action received: commit finalizing" with Subclipse 4.2.1

**Comment by markphip** [comment]
That is a new message introduced in SVN 1.9 that we have not added any code to output a message for yet.  There are probably a few more as well.  But all of the long existing messages should be correct now.
