### ISSUE TITLE
Subclipse does not support clients over Microsoft Direct Access

### ISSUE THREAD

**Issue by danieldamon** [subclipse/subclipse#104]
Microsoft Access requires support for IPV6, which eliminates using JavaHL, since that does not support IPV6.  The other connector often used is SVNKit, which does not support Windows native Kerberos authentication.

It would seem that there is no solution.  However, in the previous implementation of Subversive, when using SVNKit, the fallback would be to ask for your Microsoft credentials, then continue with the login. Now that Subversive has been replaced with Subclipse in newer Eclipse releases, this option is no longer available.

Ideally, I'd like to see JavaHL updated to support IPV6, or SVNKit updated to support Kerberos. But can we at least get back to the old Subversive solution where it asks for the password?

**Comment by danieldamon** [comment]
Should have read Microsoft Direct Access, rather than just Microsoft Access.

**Comment by markphip** [comment]
Let me run through this ...

> JavaHL does not support IPv6

I think as an absolute statement of fact this is not true. It is based on how the native JavaHL libraries were compiled. It is entirely possible the binaries we provide, which are the ones CollabNet makes available for download, do not have this support.  But if you were to build your own with that support it would work.  TortoiseSVN has IPv6 support so it is definitely possible.

> Subversive has been replaced by Subclipse

This is news to me.  I still see: http://www.eclipse.org/subversive/   Neither plugin is actively maintained anymore. AFAIK you ought to still be able to install and use Subversive if it worked for you.

> prompt for password

With the API that we use this is not possible. We are written exclusively to Subversion's API.  We provide it a callback function to prompt for password and it is entirely up to the API when and if to call that function.  We have no way to force this to happen and you cannot "push" credentials to the API either.

Your best bet would be to build your own JavaHL binaries (or find them elsewhere) and swap them for the ones we ship.
