### ISSUE TITLE
No SVN-revision shown in Eclipse Project window

### ISSUE THREAD

**Issue by starbrights** [subclipse/subclipse#105]
Looking at the project explorer I miss the revision number of each project that is checked out. It just shows the SVN path in [].
If I open the project I can see the different svn-revisions of each single file, but I don't see the summery for the project. 
Do I set something wrong, is this intended? How can I configure Eclipse/Subclipse to see this?

(I switched to Eclipse 19.06 with Subclipse from previous using Eclipse Oxygen/Subversive)

Installed is:
  Subclipse	4.3.0.201901172050	org.tigris.subversion.subclipse.feature.group	Subclipse
  Subclipse Integration for Mylyn (Optional)	4.2.0.1	org.tigris.subversion.subclipse.mylyn.feature.feature.group	Subclipse
  Subversion Revision Graph	4.2.0.1	org.tigris.subversion.subclipse.graph.feature.feature.group	Subclipse
  SVNKit Client Adapter	1.8.12.3	org.tigris.subversion.clientadapter.svnkit.feature.feature.group	Subclipse

**Comment by markphip** [comment]
You can customize the text decorators in Preferences and add the {revision} on project if desired.  I confirmed it works:

![Screen Shot 2019-07-12 at 10 51 44 AM](https://user-images.githubusercontent.com/933108/61137249-2a663580-a493-11e9-96b5-a5af3110e26b.png)

**Comment by starbrights** [comment]
You make my day - thank you so much - will test it next days!
