### ISSUE TITLE
Is there a good reason to choose JavaHL over SVNKit on Mac?

### ISSUE THREAD

**Issue by saoj** [subclipse/subclipse#114]
I've always used JavaHL but I'm having all sorts of passwords problems with JavaHL in a new installation. It does not save passwords and overwrite the saved passwords from the command-line subversion. If I use SVNKit that simply does not happen.

So my question is: what will I miss, if anything, if I switch from JavaHL to SVNKit?

I'm using Subversion 1.11 and Subclipse 4.3.0. Subclipse does not support Subversion 1.12 and 1.13, correct?

**Comment by markphip** [comment]
I usually try to use JavaHL when possible. There is a version with 1.12 support available. see https://github.com/subclipse/subclipse/issues/100

When installing Subclipse you need to check or uncheck the show all versions option so you can install the right version of the JavaHL adapter that matches the version you have installed.
