### ISSUE TITLE
Question about autoswitch to head revision

### ISSUE THREAD

**Issue by zlelik** [subclipse/subclipse#123]
I am using Subclipse with Eclipse Version: 2019-12 (4.14.0). Every time I commit to SVN or update, my project is not switched to head revision and I want to switch automatically to head revision. Otherwise, I need to do it manually every time and it is very annoying. Is there any option to change this behavior or it works as designed? In the past I used Subversive and this problem did not happen.

**Comment by markphip** [comment]
I am not sure I understand what you are asking but this all sounds like normal Subversion behavior for any client. I am about 99% sure Subversive worked the same way.

Here is something I wrote about this back in 2006:  https://markphip.blogspot.com/2006/12/mixed-revision-working-copies.html

Any file you commit will be at its HEAD revision after the commit but the working copy itself does not get updated until you take an Update option.

**Comment by zlelik** [comment]
Hi.

Thanks a lot for your help. I got it. Please close this request.

Best Regards,
Z@
