### ISSUE TITLE
Subclipse in Marketplace

### ISSUE THREAD

**Issue by Dmagos** [subclipse/subclipse#124]
I failed to find Subclipse anywhere within the Eclipse Marketplace (from Eclipse 2019-12).  Even tried to Install Software via https://github.com/subclipse/subclipse, but failed.

**Comment by markphip** [comment]
I am not sure what is going on with the Marketplace but I have raised issues with Eclipse to see if they can get it fixed or are aware of the problem.

In terms of installing direct from our update site it looks like you tried to enter the projects Github repository?  That is obviously not going to work.  You need to use the update site URL.  See the wiki and documentation here:  https://github.com/subclipse/subclipse/wiki

The update site URL's are listed there.

**Comment by agosdahu** [comment]
If you search "tag: svn" within the Eclipse marketplace, you can find Subclipse, however it is not listed as something to be installed (I'm using the 2019-12 version).
I could however install subclipse by the instructions on wiki, which led to crashing Eclipse irrepairably. (restart leads to a frozen screen)
I can reinstall an earlier version of eclipse and use Subclipse via installing from the marketplace, as a workaround for the time being.

**Comment by markphip** [comment]
I have not heard back from Eclipse yet on whether they are able to fix the marketplace listing. Installing via the update site should not be any different though. All the Markerplace does is have you tell it your update site URL and which features to install. So it is just a simpler UI to the same install experience.

**Comment by markphip** [comment]
I finally connected with the Eclipse Marketplace people. They think their script that was supposed to update our listing to say it was compatible with the 2019-12 listing messed up the data.  They have restored it back and I confirmed that the install process works now.

Thanks for letting us know about this problem.
