### ISSUE TITLE
Compare with previous on doubleclicking in Show History view

### ISSUE THREAD

**Issue by JanecekPetr** [subclipse/subclipse#15]
I feel like this has to have been asked a thousand times now, but I can't figure it out:

When in the Show History view, I'd like to configure doubleclicking a revision or doubleclicking a file in a revision to go to Compare with Previous Revision right away. I know I can rightclick and Compare..., but I'm doing this dozens of times a day and a configuration would be helpful. I think Subversive does this (?), but that has other issues...

eclipse Neon.1 (4.6.1)
Subclipse 4.2.1

**Comment by PyvesB** [comment]
This is a convenient new feature, thanks for adding it!
