### ISSUE TITLE
Subclipse update site seems to be down

### ISSUE THREAD

**Issue by SR-G** [subclipse/subclipse#158]
I'm not able to install subclipse anymore (neither through Marketplace nor directly by using https://subclipse.github.io/updates/)

Anyway even browsing that URL through chrome is not working at this time.

```
➜  ping subclipse.github.io
PING subclipse.github.io (3.220.72.65) 56(84) bytes of data.

--- subclipse.github.io ping statistics ---
5 packets transmitted, 0 received, 100% packet loss, time 11ms
```

**Comment by markphip** [comment]
I just did a Marketplace install without problems. I can also browse the site .. you only get the basic page that I put there that says you cannot really browse the site but it still comes up OK. Maybe Github Pages had a brief outage. Please use the new Discussions feature for things like this in the future. Thanks
