### ISSUE TITLE
Subclipse marketplace installation fails in STS 3.7.3 (Eclipse Mars)

### ISSUE THREAD

**Issue by haribalaji79** [subclipse/subclipse#16]
I checked the URL https://dl.bintray.com/subclipse/archive/release/1.12.x/ and there is no content.xml

![image](https://cloud.githubusercontent.com/assets/15215691/21357134/1ec265ec-c6fa-11e6-9bc5-4e5ec645559d.png)

**Comment by markphip** [comment]
There does not need to be a content.xml

It is failing because it does not like the SSL certificate.  Most likely you need to run Eclipse with a newer JVM with an updated CA bundle, you could also import the cert manually.
