### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by mngdys** [subclipse/subclipse#163]
m1 MacOS 11.1
eclipse(4.5.2) Mars
从eclipse Marketplace安装和使用url安装，都失败。
<img width="362" alt="WechatIMG165" src="https://user-images.githubusercontent.com/26875606/109457514-fa1f4080-7a95-11eb-9c79-13ad17ccad89.png">

**Comment by markphip** [comment]
What are you doing to run Eclipse on an M1 Mac? What are you using for a JVM?

The error from the JVM is "protocol_version" which usually means your JVM does not support the SSL protocol version of the site. From what I can see, GitHub only support TLS 1.2 so your JVM would have to support this protocol. We do not control the hosting infrastructure there is not a lot more we can do.

**Comment by mngdys** [comment]
谢谢您的回复，我采用了安装subclipse压缩包的形式解决了这个问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mark Phippard"<notifications@github.com&gt;; 
发送时间: 2021年3月1日(星期一) 晚上10:50
收件人: "subclipse/subclipse"<subclipse@noreply.github.com&gt;; 
抄送: "故人抱剑斩春风"<1205315867@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [subclipse/subclipse] 安装失败 (#163)






在 M1 Mac 上运行 Eclipse 要做什么？在 JVM 上用什么？

来自 JVM 的错误是“ protocol _ version ”，这通常意味着您的 JVM 不支持SSL网站的协议版本。据我所见， GitHub 只支持TLS1.2所以您的JVM必须支持这个协议。我们不能控制托管基础设施，我们也不能做更多的事情。

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看，或取消订阅.

**Comment by markphip** [comment]
Thanks for the followup.
