### ISSUE TITLE
subclipse4.3.3版本的不能离线安装吗？

### ISSUE THREAD

**Issue by mngdys** [subclipse/subclipse#166]
怎么离线安装4.3.3版本的subclipse？
在线安装不能使用

**Comment by markphip** [comment]
You can download the zipped update site here:   https://github.com/subclipse/subclipse/releases/tag/4.3.3

Note it is not complete though as it only includes the Subclipse features not the dependencies. So those may have to be obtained elsewhere.

**Comment by mngdys** [comment]
好的，谢谢您的解答。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mark Phippard"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 晚上8:33
收件人: "subclipse/subclipse"<subclipse@noreply.github.com&gt;; 
抄送: "故人抱剑斩春风"<1205315867@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [subclipse/subclipse] subclipse4.3.3版本的不能离线安装吗？ (#166)






你可以在这里下载压缩更新网站：https://github.com/subclipse/subclipse/releases/tag/4.3.3

注意，它是不完整的，因为它只包括 Sub clipse 功能，而不是依赖项。所以这些可能要从别处获得。

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看，或取消订阅.

**Comment by markphip** [comment]
You will probably need the JavaHL dependency, that can be obtained here: https://github.com/subclipse/updates/tree/main/javahl

If you are on Windows you want the 1.14.0 version. On MacOS or Linux you need to get the version that matches your installed version of native SVN client.

**Comment by mngdys** [comment]
非常感谢，这正是我所需要的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mark Phippard"<notifications@github.com&gt;; 
发送时间: 2021年3月3日(星期三) 晚上8:46
收件人: "subclipse/subclipse"<subclipse@noreply.github.com&gt;; 
抄送: "故人抱剑斩春风"<1205315867@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [subclipse/subclipse] subclipse4.3.3版本的不能离线安装吗？ (#166)






您可能需要 Java HL 依赖项，可以在这里获得：https://github.com/subclipse/updates/tree/main/javahl

如果你用的是 Windows ，你想要的是 1 . 14 . 0 版本。在 MacOS 或 Linux 上，您需要获得与您安装的本机 SVN 客户端版本相匹配的版本。

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看，或取消订阅.
