### ISSUE TITLE
SVNKit not showing as option in "SVN interface" section

### ISSUE THREAD

**Issue by darose** [subclipse/subclipse#19]
I've recently installed v4.2.2 (on Eclipse 4.6.2).  But only JavaHL shows as an interface option.

![nosvnkit](https://cloud.githubusercontent.com/assets/507237/21789967/119ad932-d6a7-11e6-9ffc-6cf9139071d4.png)

However, the SVNKit jars are definitely present:

/usr/lib/eclipse/dropins/subclipse/eclipse/features/org.tigris.subversion.clientadapter.svnkit.feature_1.8.12.1/
/usr/lib/eclipse/dropins/subclipse/eclipse/features/org.tigris.subversion.clientadapter.svnkit.feature_1.8.12.1/META-INF/
/usr/lib/eclipse/dropins/subclipse/eclipse/features/org.tigris.subversion.clientadapter.svnkit.feature_1.8.12.1/META-INF/MANIFEST.MF
/usr/lib/eclipse/dropins/subclipse/eclipse/features/org.tigris.subversion.clientadapter.svnkit.feature_1.8.12.1/feature.properties
/usr/lib/eclipse/dropins/subclipse/eclipse/features/org.tigris.subversion.clientadapter.svnkit.feature_1.8.12.1/feature.xml
/usr/lib/eclipse/dropins/subclipse/eclipse/features/org.tigris.subversion.clientadapter.svnkit.feature_1.8.12.1/license.html
/usr/lib/eclipse/dropins/subclipse/eclipse/plugins/org.tigris.subversion.clientadapter.svnkit_1.8.12.1.jar

Any ideas what the problem might be?

**Comment by markphip** [comment]
You need to have the svnkit library plugin installed too.

**Comment by darose** [comment]
Ah, sorry, didn't realize - thanks.
