### ISSUE TITLE
Internal error occurred during : "Refresh SVN status cache".

### ISSUE THREAD

**Issue by m0squito** [subclipse/subclipse#214]
I just set up a brand new MBP 16 with M1 Max, the latest Eclipse, JDK 17 from Adoptium. I installed the full version of Subclipse and each time I make a change in my source code, I get the annoying dialog informing me that "Problem Occurred". The details pane includes the information below.:
```
An internal error occurred during: "Refresh SVN status cache". 
Unable to make field private java.lang.Throwable java.lang.Throwable.cause accessible: module java.base does not "opens java.lang" to unnamed module @11f1bef3
```

Am I missing something obvious here? I can use SVN, it just gives me this error each time I save a file, so it's incredibly annoying. I can disable the cache refreshing via settings, but then I don't get the behavior that I'm used to - seeing which files changed right away.

**Comment by markphip** [comment]
I can only suggest you try switching to using the JavaHL library in place of SVNKit. Take a look at: https://github.com/subclipse/subclipse/issues/206

**Comment by m0squito** [comment]
@markphip this solved my problem, I cannot thank you enough.

I would only add that the Extensions folder was already present on my machine and the JavaHL library installed via Homebrew was in a different location, so the only command I had to issue was this:

`sudo ln -s /opt/homebrew/lib/libsvnjavahl-1.dylib /Library/Java/Extensions/libsvnjavahl-1.dylib`

After a restart, the Subclipse recognized JavaHL, and once selected, the above-described problem was gone.

Thank you!

**Comment by markphip** [comment]
Thanks for confirming. I updated the Wiki page to reflect that Homebrew default path has changed in newer versions.

**Comment by amartinwest** [comment]
I had a dilema, using javahl, I would get the repeated password prompts, I switched to svnkit and then got "Refresh SVN Cache" problem. However after some investigation I discovered there is a newer version of svnkit at [](https://svnkit.com/download.php), but the update site doesnt work due cert problem, but the archive does work. Since installing it seems to be working ok.

**Comment by JakobJoSchmidt** [comment]
> 

HiI experience the same problem you described,but Am having trouble getting the JavaHL libraries. They are not included if i download subversion via homebrew. Could you tell me where yogurt them please?

**Comment by JakobJoSchmidt** [comment]
When I  install Subversion via Homebrew I can not find the file  "libsvnjavahl-1.dylib"   on may mac.


Can    anyone help me please?

**Comment by markphip** [comment]
Homebrew stopped providing them. I think Macports still does, but not sure

**Comment by markphip** [comment]
https://github.com/Homebrew/homebrew-core/issues/122148
