### ISSUE TITLE
Apply Patch... menu item not working for some files

### ISSUE THREAD

**Issue by xerces8** [subclipse/subclipse#24]
I have subclipse 4.2.2 in Eclipse 4.6.2 (Neon.2, Java EE IDE) 

I noticed that right clicking on a file in the Project Explorer and the selecting Team/Apply Patch... does not work for some files. Nothing happens. What should happen is the "Apply Patch" dialog should appear.

It works for most files, but on some nothing happens. The only thing I see is different with those files is their size, they are 100-200 KB big.

BTW, the same problem is also in subclipse 1.10.13 in Eclipse 4.3.2

**Comment by markphip** [comment]
My recollection is that we have nothing to do with this menu item.  This comes from Eclipse itself and is one of the only items that appear on the Team menu even if you are not connected to a SVN, Git, CVS provider.  I could be wrong, but that is how I remember this.

You are going to need to dig deeper to figure out when it does not show up.  Maybe look for an error being logged in the Eclipse error log etc. as well.

Reopen if you can trace it to something we can fix.
