### ISSUE TITLE
Exception "NoClassDefFoundError: org/eclipse/ui/views/navigator/ResourceSorter" with Eclipse 4.28

### ISSUE THREAD

**Issue by ptziegler** [subclipse/subclipse#262]
The Eclipse integration of Subclipse is using the terminally deprecated ResourceNavigator and ResourceSorter which have been removed with the upcoming Eclipse release.

**Comment by markphip** [comment]
What is the backwards compatible story for the changes you are submitting? When were these new classes introduced? I think it was a very long time ago but just want to be sure in case we need to indicate which older versions will lose support.

**Comment by ptziegler** [comment]
According to the documentation, the ResourceComparator has been introduced with 3.3 and the Project Explorer with 3.5, which I assume correlates to the Eclipse releases.

The oldest Eclipse I have at hand right now is the 3.8.2, but even there, those classes have already been marked as deprecated, with the alternatives being available. Subclipse requires 4.2, so I think backwards-compatibility is ensured.

![image](https://user-images.githubusercontent.com/70652978/235131251-3c3038fd-bd68-4f9c-8b8d-6e40a6bf0964.png)

See [this](https://github.com/eclipse-platform/eclipse.platform.ui/issues/644) GitHub issue and [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549953) Bugzilla item for reference.
