### ISSUE TITLE
unable to commit file /.settings/org.eclipse.core.resources.prefs

### ISSUE THREAD

**Issue by stefan1611** [subclipse/subclipse#267]
As soon as my projects contain this file, on any commit i get the error:

org.apache.subversion.javahl.ClientException: RA layer request failed
svn: Commit failed (details follow):
svn: Unexpected HTTP status 503 'Service Temporarily Unavailable' on '/{repo-xyz}/{project-abc}/trunk/.settings/org.eclipse.core.resources.prefs'

I'm using eclipse 23-3-java-edition and subclipse 4.3.3. I'm bound to use Java 11.

It doesn't matters what SVN-interface-Client is selected at Preferences->Version Control(Team)->SVN:
"JavaHL (JNI) 1.14.0 (r1876290)" produces the errormessage above, but also
"SVNKit (Pure Java) SVNKit v1.10.1.10793" results in an error, even if the message looks completely different.

One can easily reproduce this error:
- create a simple, new Java Project with an arbitrary name, leave everything on default
- check if the file /.settings/org.eclipse.core.resources.prefs has been created by default, if so, delete it
- refresh the project in eclipse and upload it to your repository (Team->Share Project... and after that Team->Commit...); everything will be fine, then:
- create an empty file called org.eclipse.core.resources.prefs under the .settings directory
   -OR-
   go to Project->Properties->Resource->Text file encoding->Other->UTF-8 (that's what i'm originally trying to do) - so in other words make sure, Inherited from container (...) is no longer selected, klick Apply and Close; now the file /.settings/org.eclipse.core.resources.prefs should has been created (again)
- when now trying to commit that simple change, it will fail as described above

If not a bug, any help is appreciated.

Regards

**Comment by markphip** [comment]
It looks like an error with your server, not the client.

Try using the SVN command line to commit the same file from the same working copy. You will either get the same error, confirming it is a server problem, or it will work and your problem is resolved.

**Comment by stefan1611** [comment]
Since i'm not that familiar with SVN-CLI, i tested it with Tortoise-SVN i'm using on another system and it actually resulted in the same error message.

It then took me a while to convince my system administrator that it might be worthwhile to update our almost 10 year old subversion server-code. It took another while for the system administrator to set up a whole new operating system for the new subversion-server, but after all:

IT WORKS!

Thank you very much for that hint! Problem is solved.

Best Regards.
