### ISSUE TITLE
Eclipse 2023-06: Next button on "Checkout from SVN"-dialog is always disabled

### ISSUE THREAD

**Issue by rhoehener** [subclipse/subclipse#268]
New installation, new workspace, both pure Java and Java HL. Both new and existing repository locations.

![image](https://github.com/subclipse/subclipse/assets/13407181/2948e23a-e2d0-4c50-8ac4-1b1417bce043)

**Comment by markphip** [comment]
Published the latest snapshot build as 4.3.4 release
