### ISSUE TITLE
slow Performance?

### ISSUE THREAD

**Issue by AlBundy33** [subclipse/subclipse#277]
Today I've attached JProfiler to to eclipse and have seen that subclipse seems to be an CPU hotspot.
-> I have multiple projects with a lot of files and folders in my workspace.

![image](https://github.com/subclipse/subclipse/assets/6294586/e913986f-e951-4b30-8247-bcfe5a5deaf6)

Average Time looks fine but maybe invocations are a little bit high? 🤔 

Not sure if this is a bug or if subclipse just needs it't time but maybe you can have a look at it. 🙂

**Comment by markphip** [comment]
This may be addressed by #295 in the latest snapshot build
