### ISSUE TITLE
Unable to read repository at https://subclipse.github.io/updates/subclipse/4.3.x/content.xml

### ISSUE THREAD

**Issue by Xstream007** [subclipse/subclipse#292]
When I tried to install Subclipse from Eclipse Marketplace in SpringToolSuite4, I was getting the below error - 

`Unable to read repository at https://subclipse.github.io/updates/subclipse/4.3.x/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I tried to install via Install New Software option too. But I was getting the same error. The installation is not able to find content.xml file. I observed many raising the same concern on stackoverflow too, but no solution -

[Why am I getting this error trying to install Subclipse from the update site?](https://stackoverflow.com/questions/7882809/why-am-i-getting-this-error-trying-to-install-subclipse-from-the-update-site)
[unable to install subclipse with Eclipse neon3 64 bit on Windows 7 64-bit](https://stackoverflow.com/questions/43934098/unable-to-install-subclipse-with-eclipse-neon3-64-bit-on-windows-7-64-bit)

Please check.

**Comment by t14z** [comment]
你好！你的邮件已收到
