### ISSUE TITLE
Legacy Releases Links Broken

### ISSUE THREAD

**Issue by rosshaugh** [subclipse/subclipse#3]
Hi,

The Legacy Releases links are broken on the wiki page.

They are listed as being under:
https://dl.bintray.com/subclipse/archive/1.x.x

but they are instead found under: 
https://dl.bintray.com/subclipse/archive/release/1.x.x

Thanks,
Ross

**Comment by markphip** [comment]
Thanks, I have updated the wiki.  Thankfully I had entered the URL correctly in the Eclipse Marketplace listing.
