### ISSUE TITLE
Subclipse installation requires login credentials for dl.bintray.com

### ISSUE THREAD

**Issue by sakra** [subclipse/subclipse#34]
Installing Subclipse via

https://dl.bintray.com/subclipse/releases/subclipse/4.2.x/

requires login credentials for `dl.bintray.com`. This information should be added to the Installation wiki page.

**Comment by markphip** [comment]
Nothing on bintray requires credentials, it must be some hiccup on their service.

**Comment by axel3rd** [comment]
Incident reported yesterday [May, 23](https://bintray.statuspage.io/) (twitter [report](https://twitter.com/bintray/status/866984113567387648) / [anwser](https://twitter.com/bintray/status/867037717439401984)) ; but problem still occur today for Eclipse plugin update (authentication required) :(

**Comment by markphip** [comment]
Any problem clearly resides in Bintray.

Thanks for posting links to their Twitter responses but there is nothing we can do to help resolve the problems.
