### ISSUE TITLE
Password is not Saving in Neon on Mac OSX

### ISSUE THREAD

**Issue by jamiejackson** [subclipse/subclipse#38]
I reinstalled Eclipse, and now Subclipse doesn't seem to be saving my password. (It prompts me on every operation, even when I tick the save checkbox.)

What's the trick to getting it working?

eclipse.buildId=4.6.3.M20170301-0400

```
  Subclipse	4.2.2.201612131538	org.tigris.subversion.subclipse.feature.group	Subclipse
  Subclipse Integration for Mylyn (Optional)	4.2.0.1	org.tigris.subversion.subclipse.mylyn.feature.feature.group	Subclipse
  Subversion Revision Graph	4.2.0.1	org.tigris.subversion.subclipse.graph.feature.feature.group	Subclipse
  SVNKit Client Adapter	1.8.12.1	org.tigris.subversion.clientadapter.svnkit.feature.feature.group	Subclipse
  SVNKit Library	1.8.12.r10533_v20160129_0158	org.tmatesoft.svnkit.feature.group	TMate Software
```

**Comment by markphip** [comment]
Subclipse has no control over this, it is up to the API which in your case seems to be SVNKit.  The checkbox just corresponds to a boolean in the SVN API that tells it you are OK with it saving the password.  It is then up to the API to actually do it or not.

I do not know if SVNKit tries to store using the OSX Keyring or a custom file or ...

**Comment by markphip** [comment]
It does not help a lot but Google reminded me that SVNKit stores passwords in the Eclipse keyring. So perhaps it cannot for some reason.  Not sure where you go from here but that is something to look at.  I recall there are some Eclipse preferences related to the keyring.

**Comment by jamiejackson** [comment]
For what it's worth, my colleagues and I are using JavaHL with Subclipse. Does that change things?

**Comment by markphip** [comment]
Based on info provided above you are using SVNKit.

That said, JavaHL (native Subversion) stores passwords in the OSX keychain by default.  Though ultimately it is determined by what you have in ~/.subversion/config

This Stackoverflow post does not have an "answer" but the info the poster provides in their question could be useful for debugging on your end.  Maybe you will have better luck than they did by following some of the same steps.  https://stackoverflow.com/questions/44607276/subclipse-problems-accessing-svn-credentials-in-keychain-on-macos-sierra

**Comment by jamiejackson** [comment]
I'll take a look at the SO post.

In the meantime I see that my OP was misleading about the use of SVNKit. While I had the plugin component installed, I had selected _JavaHL_ as Subclipse's SVN interface:

![image](https://user-images.githubusercontent.com/479475/27964111-1f827722-6305-11e7-9808-151acc54584e.png)

For kicks, I've now completely removed the SVNKit components, and a search for `sub` in Eclipse Installation Details yields:

* Maven SCM handler for Subclipse	1.0.0.201609101315	org.sonatype.m2e.subclipse.feature.feature.group	Subclipse
  * Subclipse	4.2.2.201612131538	org.tigris.subversion.subclipse.feature.group	Subclipse
* Subclipse Integration for Mylyn (Optional)	4.2.0.1	org.tigris.subversion.subclipse.mylyn.feature.feature.group	Subclipse
* Subversion Revision Graph	4.2.0.1	org.tigris.subversion.subclipse.graph.feature.feature.group	Subclipse

For what it's worth, the problem remains.

I'd also tried the default SVN config file, as well as with `password-stores = keychain`, but that made no difference.

On to SO...

**Comment by jamiejackson** [comment]
I seem to have solved it. From OSX's "Keychain Access" app, I see an entry under Category > Passwords for the SVN server. On that entry, I:

* Double-clicked
* Access Control
  * Ensure "Confirm before allowing access" is selected.
  * Select "Eclipse" and remove it with the "-" button.
  * Click "Save Changes" button

Back in Eclipse, perform an SVN operation. A dialog will appear: "Eclipse wants to use your confidential... Do you want to allow access to this item? Choose "Always Allow".

Now I don't have to login for every operation.

Side note: It doesn't seem to matter (to Subclipse, anyway) whether the SVN config file has `password-stores = keychain` commented in or out. I tried it both ways (redoing the whole process above), and it worked.
