### ISSUE TITLE
Lock code while other team member cannot edit

### ISSUE THREAD

**Issue by chung1412** [subclipse/subclipse#40]
I was wondering if I can check out my code so that another team member cannot edit it until I check in my code. 
I was looking at team in eclipse but cannot find this function

**Comment by markphip** [comment]
You cannot prevent another user from editing the file, but if you do Team > Lock you can prevent them from committing.

SVN supports a property named `svn:needs-lock` that can be set on files. When this property is set, the files are made read-only when they are checked out that is meant to be a signal to the user that they need to lock the file before editing.  When using Subclipse in Eclipse, when you try to edit a file with this property set it will prompt you to lock the file first.  If another user has it locked, the lock will fail.  That is the best that can be done to prevent another user editing.  See this chapter in the SVN Book:  [http://svnbook.red-bean.com/en/1.7/svn.advanced.locking.html](http://svnbook.red-bean.com/en/1.7/svn.advanced.locking.html)
