### ISSUE TITLE
"Set Commit Properties" dialog does not use Eclipse Colors / not Dark Theme Compatible

### ISSUE THREAD

**Issue by wodencafe** [subclipse/subclipse#45]
When I use the "Set Commit Properties" option in SVN History View,
the dialog does not use Eclipse's Colors / follow the Dark Theme.

![screen03](https://user-images.githubusercontent.com/9727493/28432581-020ef60e-6d4e-11e7-84cf-eeae93f14644.png)

Also, the "Previously Entered Comment" Dropdown is unnecessarily wide, cutting off the text on the left side.
This becomes apparent when resizing this Dialog Window.

**Comment by selsemore** [comment]
This as well as Issue #44 was caused by an Eclipse bug:  

https://bugs.eclipse.org/bugs/show_bug.cgi?id=539441

Fortunately it was simple to work around it.
