### ISSUE TITLE
SVN Rev Properties

### ISSUE THREAD

**Issue by maxskywalker** [subclipse/subclipse#46]
The view of  " SVN Rev Properties "  doesnit work???? It can't load reversion information  from svn server., because I compared it with TortoiseSVN. Thank you!

**Comment by maxskywalker** [comment]
The view of the SVN Rev Properties can work now after I changed ths source code of subclipse? But I don't understand   how it can commit the svn:log, svn:date, svn:username of reversion properties  when commit the changed file to the svn server? Someone can help me? Thank you!

**Comment by markphip** [comment]
svn:log comes from the commit message provided to the commit API.  The user and date cannot be set by the client during a commit.  The server sets those properties.  The user comes from the username used to authenticate with the server and the date of course is based on the clock of the server.

**Comment by maxskywalker** [comment]
Thank you very much for your patient answer. Now, I have understanded it.And I will try to resolve it in soon afterwards. Wish everything goes well with you ! Thank you again.

**Comment by maxskywalker** [comment]
SVNCommitClient commitClient = clientManager.getCommitClient();
  Map<String, String> map = new HashMap<String, String>();
 map.put("hik:project", "TestProject");
 // TODO add custom svnProperties
SVNProperties svnProperties = new SVNProperties();
SVNProperties svnPropertiesAdd = svnProperties.wrap(map);
 commitInfo = commitClient.doImport(localPath, dstUrl, commitMessage, svnPropertiesAdd, false, false, SVNDepth.INFINITY);

Now, I can use the api of svnkit.jar to add some custom revision property ("hik:project", "TestProject") to the svn server when I commited some file to the svn server. But I can't find the same implemation of CommitAction.java or CommitOperation.java in the project of subclipse.ui. Would you give me advice? I'm  sorry to trouble you again!  Thank you?

**Comment by maxskywalker** [comment]
Hello, markphp. I finished the work of subclipse。I decompiler the svnkit.jar and adapter-javahl.jar, and change the commit method of AbstractJhlClientAdapter.java。so, I can commit Custom revision properties. 
Thank you very much for your assistance. Good luck with you. @markphip
