### ISSUE TITLE
Enable/Disable "Refresh SVN status cache"

### ISSUE THREAD

**Issue by marcgise** [subclipse/subclipse#48]
I have a process that modifies a lot of files in the Workspace. The problem is that each time a file is modified, a background Job named "Refresh SVN status cache" is executed, and it slow down my process drastically.

It would be great if there exists a preference that allows to enable/disable this Job. This way, previously to execute my process, I disable the Job, and once ended, I enable it again.

I consider it necessary, as it is reducing a lot my productivity.

I found that the file that starts the Job, is org.tigris.subversion.subclipse.core.resourcesListeners.FileModificationManager.

Some approach like the one for derived resources, maybe is valid to solve this issue.

**Comment by marcgise** [comment]
I have modifies 5 files in the subclipse.core and subclipse.ui projects to add this functionality ;)

Cheers,

[changes.zip](https://github.com/subclipse/subclipse/files/1217571/changes.zip)

**Comment by HBuender** [comment]
I have a very similar [probelm](https://groups.google.com/forum/#!topic/subclipse/Ntbl_SfxUrg) and a quick test of your solution worked well. 
Is there a pull-request containing the changes?

**Comment by markphip** [comment]
We merged a version of this option to add a preference and will include it in the 4.3 release. Hopefully it will help.
