### ISSUE TITLE
Subclipse 4.2.3 for eclipse unable to locate JavaHl

### ISSUE THREAD

**Issue by look4kap** [subclipse/subclipse#51]
The new update is looking for JavaHL 1.9.4 in the plugins folder(org.tigris.subversion.clientadapter.javahl.win64_1.9.4) which isnt getting downloaded along with install. Copied it from another m/c for it to show up on preference->team->svn.

**Comment by benhjt** [comment]
I'm also having this problem in eclipse oxygen one (4.7.1). @look4kap can you explain what you copied from where and to in order for this to work?

**Comment by PhilClegg** [comment]
I was able to solve this by installing a version of SVN that had the JavaHL 1.9.4 included. I'm sure you can use any SVN client but just for reference the one I used was located at: http://www.sliksvn.com/en/download. I installed the latest 64 bit on that site (Just basic install, nothing fancy added). Once installed I restarted my Eclipse (oxygen in my case) and under preference->team->svn it no longer showed unavailable, it now shows "JavaHL (JNI) 1.9.7-SlikSvn (SlikSvn/1.9.7)".

**Comment by wagnerma** [comment]
I have the same issue with oxygen 4.7.1a

**Comment by markphip** [comment]
I've not seen this problem before.  There was a problem just fixed where the Windows JavaHL DLL's were not including the Windows MSVC runtime it needed so they did not load.  I wonder if that this the problem that was being seen?  This would show up as JavaHL not being available at runtime, not a problem during the install itself.

**Comment by chriskeeble** [comment]
Also having this problem. After upgrading to Eclipse Oxygen (4.7.3) and installing all updates, I have now spent nearly 2 hours attempting to get Subclipse running / installed again without any success.

**Comment by chriskeeble** [comment]
...and various resources keep pointing to this reference (including historical posts of your own on StackOverflow) which appears to be very out-of-date, unless I am misunderstanding something:

http://subclipse.tigris.org/wiki/JavaHL

**Comment by chriskeeble** [comment]
Restarting Windows, installing JRE latest release, and now get errors from Eclipse on Startup...

Java was started but returned exit code=13

**Comment by markphip** [comment]
I think I fixed it.  The issue would only be when doing a Marketplace install.

I tried it from a Windows computer and I noticed that the JavaHL plugin was not even being installed.  After the install is over, if you just do the Install/Update option and select the Subclipse update site from the drop-down, then JavaHL shows up in the list of plugins to install.  If you select it and install it then everything works.

I *think* I have fixed the problem in our Eclipse Marketplace listing that was causing this.  I will try to confirm and one way or another get that fixed.  But the easy workaround if you have already installed Subclipse is to just go to the Install/Update option and select the Subclipse update site.  Then choose the JavaHL Windows binaries option.

**Comment by markphip** [comment]
I have confirmed the Marketplace fix has worked properly.  Thanks for the nudge and sorry this took so long to correct.

**Comment by chriskeeble** [comment]
Hi Mark,

Thanks for the quick response.
I've tried to update, by going to Help > Eclipse Marketplace... > Installed, selecting Subclipse 4.2.3 and clicking "Update" but this simply changes to "Update Pending" and nothing happens?

**Comment by chriskeeble** [comment]
Having uninstalled Subclipse via the Marketplace and then reinstalled all seems to be working, and I could see the JavaHL component during install options selection.

Thank you for fixing so quickly Mark.

**Comment by Hela408** [comment]
Hi, i have this exception any help please
java.lang.NoClassDefFoundError: org/apache/subversion/javahl/ClientException
