### ISSUE TITLE
Cannot install Subclipse 1.10.x plug-in in 64 bits Windows 10

### ISSUE THREAD

**Issue by ZijianQi** [subclipse/subclipse#53]
When I try to install Subclipse 1.10.x from "http://subclipse.tigris.org/update_1.10.x", I got this error: 

    
    An error occurred while collecting items to be installed
    session context was:(profile=C__Users_eclipse_jee-neon_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
    No repository found containing: osgi.bundle,org.tigris.subversion.clientadapter.javahl,1.8.15
    No repository found containing: osgi.bundle,org.tigris.subversion.clientadapter.javahl.win64,1.8.15
    No repository found containing: osgi.bundle,org.tigris.subversion.subclipse.mylyn,3.0.0

My environment:
Windows 10, 64 bits
Eclipse Neon.3 Release (4.6.3)
SVN 1.8.17 (r1770682)
Java version "1.8.0_121", Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

And I have also tried to install Subclipse 4.2.3, it fails too. The completed description is at [StackOverflow](https://stackoverflow.com/questions/47763481/cannot-install-subclipse-plug-in-in-eclipse). (Sorry to asked there, because I cannot upload photo at github)

**Comment by marcolopes** [comment]
What happened to subclipse.tigris.org ?

**Comment by markphip** [comment]
tigris.org was shut down this was partly why we moved this project to Github several years ago.
