### ISSUE TITLE
SVN 1.10 support

### ISSUE THREAD

**Issue by ghost** [subclipse/subclipse#59]
SVN 1.10 has now been released, so when can we expect to get an updated plugin to support this new release ??

**Comment by rkuchibhatla** [comment]
I updated subversion using home brew and now, my eclipse and all other clients are failing due to incompatible svn client adapter.

any my bad luck, I tried to go back to previous version of subversion and home brew does not have it.

I always get the below error

**Incompatible JavaHL library loaded.  Subversion 1.9.x required.**

<img width="503" alt="image" src="https://user-images.githubusercontent.com/14282948/39260977-dfca836c-486f-11e8-963a-f94a54a1ca1d.png">


<img width="629" alt="image" src="https://user-images.githubusercontent.com/14282948/39260946-c217e698-486f-11e8-9fdc-629508b22539.png">

**Comment by markphip** [comment]
If you cannot get SVN 1.9 installed again you will need to install and use SVNKit.

**Comment by rkuchibhatla** [comment]
It seems even SVNKit is available for 1.9.X only

**Comment by markphip** [comment]
Yes, there is no SVN 1.10 support.  I was simply saying if you install SVNKit, Subclipse will work again for you even though you have SVN 1.10 installed.

**Comment by SuperPat45** [comment]
SVN 1.10 add the option to cleanup pristines directory:
`svn cleanup --vacuum-pristines`
Can you add this option when using the cleanup menu in the next sublcipse version?

**Comment by ronnyfm** [comment]
Thanks @markphip adding the update site to Eclipse (at least on Mac) helps to solve the issue.

**Comment by movedoa** [comment]
any news on this?

**Comment by jeffbuhrt** [comment]
From https://bugzilla.redhat.com/show_bug.cgi?id=1595101
The workaround on Fedora 28 is to do: sudo dnf downgrade subversion-javahl
I just fought the Subclipse broke again myself. And I am working again.

**Comment by jeffbuhrt** [comment]
From https://bugzilla.redhat.com/show_bug.cgi?id=1595101
The workaround on Fedora 28 is to do: sudo dnf downgrade subversion-javahl
I just fought the Subclipse broke again myself. And I am working again.

**Comment by agoertz-fls** [comment]
Half a year later this should really be tackled as more and more distros are switching to 1.10 (Fedora 28/Ubuntu 18.10/Arch/etc.)

**Comment by markphip** [comment]
As has been noted in this issue, a version with SVN 1.10 support has been posted. We do not control what Fedora packages. If they are not providing Subversion 1.10 then they could update their Subclipse version accordingly too.

**Comment by work-ed** [comment]
This fixed the issue I opened as well. https://github.com/Homebrew/homebrew-core/issues/33250

**Comment by ShareFY** [comment]
Is this problem solved? My computer is a MacBook pro, how can I add svn 1.10 support?

**Comment by ShareFY** [comment]
> It will be a while before I do any kind of official release, but I have started the process. The build on the snapshot update site now requires JavaHL 1.10. There are some issues with the update site I need to work out still though. It works fine from OSX but not Windows. For Windows, you can make it all work by using these two update sites:
> 
> Subclipse: https://dl.bintray.com/subclipse/snapshots/subclipse/master/
> JavaHL Binaries: https://dl.bintray.com/subclipse/releases/javahl/snapshots/
> 
> The site that should be working though (and does from OSX) is the one we have in our wiki:
> 
> https://dl.bintray.com/subclipse/snapshots/

how to use these sources in my mac eclipse?

> Thanks @markphip adding the update site to Eclipse (at least on Mac) helps to solve the issue.

how ? I have the same problem，but i don't konw how to solve...Can you help me?

**Comment by ShareFY** [comment]
> It will be a while before I do any kind of official release, but I have started the process. The build on the snapshot update site now requires JavaHL 1.10. There are some issues with the update site I need to work out still though. It works fine from OSX but not Windows. For Windows, you can make it all work by using these two update sites:
> 
> Subclipse: https://dl.bintray.com/subclipse/snapshots/subclipse/master/
> JavaHL Binaries: https://dl.bintray.com/subclipse/releases/javahl/snapshots/
> 
> The site that should be working though (and does from OSX) is the one we have in our wiki:
> 
> https://dl.bintray.com/subclipse/snapshots/

I've looked at wiki content, but I don't know how to solve this problem on my MAC. I don't know how to use these files。。。

**Comment by markphip** [comment]
This is now available in the released 4.3.0 version
