### ISSUE TITLE
History compare doesn't handle added files correctly

### ISSUE THREAD

**Issue by xerces8** [subclipse/subclipse#6]
Originally reported here:
http://subclipse.tigris.org/ds/viewMessage.do?dsForumId=1047&dsMessageId=3102588

Here is the text amended to match my current problem:

In the history view of a folder I clicked a revision and selected Compare... and clicked OK

Issues:
- The order is reversed. Added items (files) are marked with minus sign.
- opening an added (shown with minus sign...) file fails (two empty file contents are shown) with this messages in log (repeated 10 times for some reason):
  (1234 is the older revision)
  
  Two versioned resources are unrelated
  svn: Unable to find repository location for 'https://svn-server.e​xample.org/repos/MY/​apple/juice/xxx/src/​main/java/a/b/Some.j​ava' in revision 1234
  
  Filesystem has no item
  svn: '/repos/MY/!svn/bc/1​234/apple/juice/ xxx/src/main/java/a/b/Some.java ' path not found

In the Synchronize view added/deleted items can be compared without problems (the other/missing file is shown as if empty).

Eclipse Java EE IDE for Web Developers.

Version: Neon.1 Release (4.6.1)
Build id: 20160913-0900
  Subclipse 4.2.0.201609101435  org.tigris.subversion.subclipse.feature.group   Subclipse

**Comment by rocketnewton** [comment]
This is still happening with the latest version... :(
