### ISSUE TITLE
Provide more detailed installation instructions -and/or- more clearly state (required) and (optional) for installation in Eclipse

### ISSUE THREAD

**Issue by maettu-this** [subclipse/subclipse#61]
When "Install New Software…" from [https://dl.bintray.com/subclipse/releases/subclipse/latest/](https://dl.bintray.com/subclipse/releases/subclipse/latest/) in Eclipse, I get the list as shown below:

![abb - svn - 00 - eclipse - install](https://user-images.githubusercontent.com/24897735/39465444-aec48a7a-4d23-11e8-9a90-5422d0d97d4c.png)

Now, what do I **have** to install? Of course, I could just install them all. But, being cautious with installing things I don't need, I only want to install what is really necessary. And this is neither obvious nor well documented at [https://github.com/subclipse/subclipse/wiki](https://github.com/subclipse/subclipse/wiki) nor [https://github.com/subclipse/subclipse/wiki/JavaHL-on-Windows](https://github.com/subclipse/subclipse/wiki/JavaHL-on-Windows).

Thus suggesting that it's either clearly stated what is (required) for those parts that are really needed. (Note that this seems inconsistent, since currently "Core SVNKit Library" is (required) but some time ago wasn't.) In addition, suggesting to better describe what must and what could be installed on the wiki.

Thanks.

**Comment by markphip** [comment]
Made an attempt to improve the wiki.
