### ISSUE TITLE
Not able to connect to subclipse repository trough network with active proxy

### ISSUE THREAD

**Issue by rea-al** [subclipse/subclipse#62]
I am having some troubles to connect to the subclipse Eclipse repository trough a network with proxy to get the latest version of the plugin.

Attached is the [subclipse.log](https://github.com/subclipse/subclipse/files/1975963/subclipse.log) file with the error details.

Steps to reproduce the issue:
1. Install the subclipse plugin from the Eclipse Marketplace or the Install New Software options on the menu bar of the Eclipse installation

**Comment by markphip** [comment]
Looks like it works your Java version just does not trust the SSL cert used by bintray.com.  A newer JVM might be OK since I've not seen this.  Others have though, you are not the first.  Nothing we can do about it though.

**Comment by rea-al** [comment]
So @markphip, are you saying that changing the JVM should address the problem?
