### ISSUE TITLE
Unable to locate JavaHl with subclipse-4.2.4.zip update site package

### ISSUE THREAD

**Issue by rea-al** [subclipse/subclipse#63]
I am trying to install the included JavaHL feature from the subclipse-4.2.4.zip update site package but it is not displayed on the list of items in the Install Wizard.

Environment:
- eclipse.buildId=4.7.3.M20180330-0640
- java.version=1.8.0_161
- java.vendor=Oracle Corporation
- BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
- Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/C:/Users/<user_directory>/Work/Eclipse/workspace/

Steps to reproduce the issue:
1. Download the subclipse-4.2.4.zip from [this](https://dl.bintray.com/subclipse/releases/subclipse/:subclipse-4.2.4.zip) location on a known directory
2. Go to the Install Wizard trough Help/Install New Software... options located on the menu bar of an Eclipse installation
3. Click on the Add... button on the Install Wizard
4. Click on the Archive... button of the Add Repository dialog
5. Locate and select the subclipse-4.2.4.zip downloaded on the known directory from step 1
6. Press the OK button
7. Notice that JavaHL feature is not displayed on the list of items to install

**Comment by markphip** [comment]
The JavaHL DLLs live in a separate update site so they are not part of the zipped download.  You would have to download the zipped download for that update site as well:   https://bintray.com/subclipse/releases/download_file?file_path=javahl%2Fsubclipse-javahl-1.9.7.zip
