### ISSUE TITLE
Problem with installing the latest version on Eclipse Oxygen.3 (4.7.3)

### ISSUE THREAD

**Issue by jmar83** [subclipse/subclipse#64]
Hi there

I get that error message, can't install it, when i try to install the latest version on Eclipse Oxygen.3 (4.7.3):

An error occurred while installing the items
session context was:(profile=epp.package.php, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]com.collabnet.subversion.merge 4.2.0.1, action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.InstallBundleAction).
The artifact file for osgi.bundle,com.collabnet.subversion.merge,4.2.0.1 was not found.

The OS i use is a an old Windows Server 2003 32 Bit with most current SP and all updates installed. The JVM i use is from "zulu": zulu8.25.0.3-jdk8.0.153-win_i686

The update URL i used is: https://dl.bintray.com/subclipse/releases/subclipse/latest/

With best regards,
Jan

**Comment by jmar83** [comment]
The 4.2 version works, but after installation i get the following error when i try to create a new project, can't create projects anymore because of the error:

Problems encountered while setting project description.
  Cannot create linked resource '/.org.eclipse.dltk.core.external.folders/.link1'.  The parent resource is not accessible.


Regards,
Jan

**Comment by jmar83** [comment]
There is no folder called "org.eclipse.dltk.core.external.folders" or something like that in the eclipse application directory...

Regards,
Jan

**Comment by jmar83** [comment]
"There is no folder called "org.eclipse.dltk.core.external.folders" or something like that in the eclipse application directory..."

Maybe that problem was caused by another issus, MAYBE... (?)

Regards,
Jan

**Comment by jmar83** [comment]
"Maybe that problem was caused by another issus, MAYBE... (?) i try to investigate now..!!"

Yes, it was caused by your plugin - not by the xdebug/php version config which i was thinking firstly...!!

How to solve?!?

Regards,
Jan

**Comment by jmar83** [comment]
"There is no folder called "org.eclipse.dltk.core.external.folders" or something like that in the eclipse application directory..."

It is in the .metadata directory... now i deleted that .metadata dir, but the problem it now my workspace settings are all gone - that can't be serious, not really...

Regards,
Jan

**Comment by markphip** [comment]
There is nothing we can do to help you.  The "DLTK" stuff is the Eclipse Dynamic Language Toolkit which is the base plugin for a lot of languages like Perl, Python and probably PHP.  No idea what the message is about.

**Comment by jmar83** [comment]
However, i think i will switch to git anyway...

Regards, Jan
