### ISSUE TITLE
Externals at specific revision are treated as a merge "best practice" failure

### ISSUE THREAD

**Issue by dougg3** [subclipse/subclipse#66]
I've been doing research about externals and have come to the conclusion that it is a best practice when using svn:externals to specify the externals at a particular revision, e.g.:

`https://url/to/external@12345 name_of_external`

I recently switched to doing this in my projects, and I have to agree that it is a lot safer to do. However, now I'm finding that this causes a failure in Subclipse's "merging best practices" pre-check because the externals are a different revision than the rest of the project checkout. I don't think this should be treated as a failure of the merging best practices when attempting to merge. I totally understand that a mixed-revision checkout is bad for merging, but in my opinion, externals set to a specific revision shouldn't count toward that check.

If it matters, the externals causing this problem are pointing to other locations inside of the same repository.

**Comment by selsemore** [comment]
The "Working copy at a single revision" check ignores externals.  The warning is probably because the working copy revision of your project does not match the revision of its (non-external) children if you have committed property changes to the project without updating to HEAD after.

**Comment by dougg3** [comment]
@selsemore That's not it; I'm updating my entire checkout prior to attempting a merge. What you described would be an obvious reason for the best practices check to fail, but in my case it's appearing on a fully-updated checkout.

Is it possible that because my "externals" point to somewhere else in the same repository, that they aren't being ignored?

**Comment by dougg3** [comment]
@selsemore Weird! I'm using the latest Subclipse release (https://dl.bintray.com/subclipse/releases/subclipse/latest/). Here are commands I executed to create a quick repository to demonstrate the problem:

    cd /tmp
    svnadmin create testrepo
    cd ~
    svn co file:///tmp/testrepo
    cd testrepo
    svn mkdir tags branches trunk
    touch trunk/test.txt
    svn add trunk/test.txt
    svn mkdir trunk/ext
    svn commit -m "Test commit 1"
    svn propset svn:externals "^/trunk/test.txt@1 ext/test.txt" trunk
    svn commit -m "Test commit 2"
    svn update

Now, check out the project in Eclipse:

* File -> New -> Other...
* Choose "SVN -> Checkout Projects from SVN", click Next
* Create a new repository location, and enter: file:///tmp/testrepo
* In the "Select Folder" screen, choose trunk and click Next
* Choose "Check out as a project in the workspace", leave everything else as defaults
* Click Finish.
* Now there is a change detected in the project because the .project file was created, so go ahead and commit that inside of Eclipse by right-clicking on the project, and choosing Team->Commit. Doesn't matter what the commit message is.
* Update the checkout (right-click on the project, choose Team -> Update to HEAD)

So at this point it shouldn't be a mixed-revision checkout (except obviously we are forcing revision 1 of test.txt as an external, which I would argue should be ignored by the pre-merge best practices check). Finally, even though there aren't any branches yet, just try to do a merge:

* Right-click on the project and choose Team -> Merge. Choose "Merge a range of revisions" and make sure "Perform pre-merge best practices checks" is checked.
* Click Next.

When I do this, it says "Working copy is not ready for merge".

**Comment by markphip** [comment]
This example is using a file external which I doubt we ever coded for since it did not exist at the time this was created and I doubt Steve is testing. I am not sure what the Best Practices check ought to be with these as I am not even sure what SVN does with them during a merge. They are not a commonly used feature.

**Comment by selsemore** [comment]
Thanks for the detailed recipe.  Mark is right, the problem was related to file externals, which I had not been testing.

**Comment by dougg3** [comment]
Thank you so much! I'm sorry I didn't specify initially that I was using file externals. I actually didn't realize that it was only the file externals that were causing the issue, or I would have mentioned it sooner.
