### ISSUE TITLE
Compare With / Revision... missing for folders

### ISSUE THREAD

**Issue by xerces8** [subclipse/subclipse#7]
Original report: http://subclipse.tigris.org/ds/viewMessage.do?dsForumId=1047&dsMessageId=3110230

checkouts from SVN, the context menu Compare With / Revision... is grayed out for folders (in the Project Explorer view).

As a workaround I use Compare With / Branch/Tag... and enter the same URL as the existing files are from.

Is there a reason Compare With / Revision... is disabled?

Eclipse Java EE IDE for Web Developers.

Version: Neon.1 Release (4.6.1)
Build id: 20160913-0900
Subclipse 4.2.0.201609101435 org.tigris.subversion.subclipse.feature.group Subclipse

**Comment by selsemore** [comment]
The reason for Compare with Revision being disabled for folders was that the Structure Compare section of the compare editor is used for the revision selection list, with the diff against the selected revision being shown in the bottom section.  For a folder compare, however, the Structure Compare section needs to show the changed folders/files.  The "fix" was to make the Compare to Version option, when a folder is selected, first show a revision selection dialog and then open the compare editor against the selected revision.
