### ISSUE TITLE
Unable to install,can not read content.xml

### ISSUE THREAD

**Issue by yitengpl** [subclipse/subclipse#71]
Hello,

When I install subclipse from Eclipse Marketplace(my eclipse version is luna),an error occurred like this:

Unable to read repository at https://dl.bintray.com/subclipse/releases/subclipse/4.2.x/content.xml.

java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:168)

Can anyone tell me how to solve it?
thanks!

**Comment by doducviet** [comment]
Try Zipped Update Sites
https://dl.bintray.com/subclipse/releases/subclipse/

**Comment by yitengpl** [comment]
@doducviet ：
 Thank you for your reply!
I have tried,but the same error occurred.

**Comment by yitengpl** [comment]
I found the subclipse directory（https://dl.bintray.com/subclipse/releases/subclipse/4.2.x）contain the files below：
compositeArtifacts.xml
compositeContent.xml
But the file content.xml doesn't exist.
Why?
The file content.xml is renamed to compositeContent.xml?How to fix it...

**Comment by PauloDC** [comment]
I am seeing the same error yitengpl mentioned: Unable to read https://dl.bintray.com/subclipse/releases/subclipse/4.3.x/content.xml. Happens that there is no content.xml in that URL, only compositeArtifacts.xml and compositeContent.xml.

**Comment by markphip** [comment]
The reference to content.xml is a red herring.  Eclipse is just having a problem reading the files from the site.  We cannot do much about that on our end.  It happens.  Lots of Eclipse plugins are hosted at bintray.com.  I've seen some posts about older JVM's having problems but in general I think the CDN just has hiccups serving data.  If needed download the zipped site.
