### ISSUE TITLE
Subclipse Consolve View is not legible in Dark Theme

### ISSUE THREAD

**Issue by garydgregory** [subclipse/subclipse#78]
Subclipse Consolve View is not legible in Dark Them (Eclipse 4.9.0.)

**Comment by selsemore** [comment]
Assuming that you don't have reason to frequently switch back and forth between themes, it's easy to work around this problem.  `Preferences -> Team -> SVN -> Console` and then pick the `Command Line`, `Message` and `Error` colors that work for you.  That being said, these console color preferences are certainly not theme friendly.  Maybe we should do away with these preferences altogether and just use system colors that seem appropriate?

![image](https://user-images.githubusercontent.com/1742317/50216075-1aff8d80-0385-11e9-8903-6609e6a14c13.png)
