### ISSUE TITLE
mac os lib not contain  libsvnjavahl-1.dylib

### ISSUE THREAD

**Issue by lpxiangyan9** [subclipse/subclipse#89]
homebrew install subversion 1.11.1 but not find the libsvnjavahl-1.dylib[
<img width="1541" alt="lib" src="https://user-images.githubusercontent.com/12522919/51727029-11182b00-20a5-11e9-8a10-854a73dfa849.png">
](url)

**Comment by markphip** [comment]
You have to use `brew install subversion --with-java`

**Comment by lpxiangyan9** [comment]
mark the warning this formula has no --with-java option so it will be ignored! so no javahl

**Comment by markphip** [comment]
It looks like they just removed it:

https://github.com/Homebrew/homebrew-core/pull/36217

**Comment by markphip** [comment]
It is being fixed

https://github.com/Homebrew/homebrew-core/pull/36387
