### ISSUE TITLE
brew install subversion --with-java  Error: invalid option: --with-java

### ISSUE THREAD

**Issue by linxiangqian** [subclipse/subclipse#93]
When I run the commond : brew install subversion --with-java 
It throw the error:  Error: invalid option: --with-java
What is the reason?

**Comment by markphip** [comment]
About a month ago Homebrew removed the --with-java option. However, they just made it part of the default install so you only need to run `brew install subversion`.  I have fixed the wiki page.

**Comment by linxiangqian** [comment]
Than you !
