### ISSUE TITLE
broken link to release 4.3.x in Eclipse Marketplace

### ISSUE THREAD

**Issue by arware** [subclipse/subclipse#99]
broken link to release 4.3.x in Eclipse Marketplace.

**Comment by markphip** [comment]
Can you be more specific?  Nothing has changed and it has been installed over 100K times from the marketplace. Was it just a dl.bintray.com error?

**Comment by arware** [comment]
I'm trying to install Subclipse to Code Composer Studio 6.2 from TI. The Eclipse Marketplace instructs to "Drag to your running Eclipse * workspace. * Requires Eclipse Marketplace Client". Once its drugged, it tries to access https://dl.bintray.com/subclipse/releases/subclipse/4.3.x/ folder, and fails to see context.xml file.
I downloaded the zip archive for both 4.30 and 4.24, and it still fails.
**I had a good run in the past!** Extremely helpful plugin for SVN access and team sharing.

**Comment by markphip** [comment]
I normally use the marketplace client UI and just select Subclipse from the list of plugins, but do not believe it would matter.  We do not control any of this regardless. We just publish the site. Assuming they offer a URL to add an update site you ought to be able to add the above URL as a site. That is the correct URL and you can see the XML files if you browse it.  It is a composite update site so the file names are compositeContext.xml etc.

**Comment by arware** [comment]
Well, here is the result of 35 minutes struggle.
It's probably Code Composer Studios issue. I'll take it to them. 
![image](https://user-images.githubusercontent.com/11847239/56916558-07201280-6a6e-11e9-8fb7-9fc4a6cc4bce.png)
**Thank you for the prompt response!** Please keep this report open, I'll post solution when solve it.

**Comment by markphip** [comment]
I just downloaded latest Eclipse and did the drag and drop technique and it worked fine.

There is nothing odd about your screenshot.  It just shows you selected to install a couple items it cannot install because you do not have their dependencies.  That is not a problem.  Obviously you are installing from a zipped archive here.  That does not include any dependencies like the online composite update site does so that all makes sense.  Just do not install those plugins.

**Comment by arware** [comment]
I have to admit, I'm trying to install the plugin to an older version of Code Composer Studio, Ver 6.20. TI is up to ver. 9.x now. Let me try ver. 9.x and report success.

**Comment by arware** [comment]
Worked fine with Code Composer Studio Ver. 9.0.1.
